#!/usr/bin/env sh
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202210292159-git
# @@Author           :  Jason Hempstead
# @@Contact          :  git-admin@casjaysdev.pro
# @@License          :  LICENSE.md
# @@ReadME           :  brightness --help
# @@Copyright        :  Copyright: (c) 2022 Jason Hempstead, Casjays Developments
# @@Created          :  Saturday, Oct 29, 2022 22:19 EDT
# @@File             :  brightness
# @@Description      :  Change the screen brightness on samsung chromebook 2 (kevin)
# @@Changelog        :  newScript
# @@TODO             :  Refactor code
# @@Other            :
# @@Resource         :
# @@Terminal App     :  no
# @@sudo/root        :  no
# @@Template         :  bash/system
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[ -w "/sys/class/backlight/backlight/brightness" ] || exit 1
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
cur_bri=$(cat "/sys/class/backlight/backlight/brightness")
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
if [ "$1" = "max" ]; then
  echo "4000" >"/sys/class/backlight/backlight/brightness"
elif [ "$1" = "50" ]; then
  echo "2000" >"/sys/class/backlight/backlight/brightness"
elif [ "$1" = "min" ]; then
  echo "100" >"/sys/class/backlight/backlight/brightness"
elif [ "$1" = "up" ]; then
  bri=$(($cur_bri + ${2:-40}))
  [ "$bri" -gt 4000 ] && exit || echo $bri >"/sys/class/backlight/backlight/brightness"
elif [ "$1" = "down" ]; then
  bri=$(($cur_bri - ${2:-40}))
  [ "$bri" -lt 100 ] && exit || echo $bri >"/sys/class/backlight/backlight/brightness"
elif [ "$1" = "-s" ]; then
  echo "${2:-2000}" >"/sys/class/backlight/backlight/brightness"
else
  echo "$cur_bri"
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End script
